# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x12\x44\x65leteUserResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x12\n\x10ListUsersRequest\")\n\x11ListUsersResponse\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\"#\n\x0cUserResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User2\x8d\x02\n\x0bUserService\x12/\n\nCreateUser\x12\x12.CreateUserRequest\x1a\r.UserResponse\x12\x31\n\x0bGetUserById\x12\x13.GetUserByIdRequest\x1a\r.UserResponse\x12/\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\r.UserResponse\x12\x35\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponse\x12\x32\n\tListUsers\x12\x11.ListUsersRequest\x1a\x12.ListUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=15
  _globals['_USER']._serialized_end=62
  _globals['_CREATEUSERREQUEST']._serialized_start=64
  _globals['_CREATEUSERREQUEST']._serialized_end=112
  _globals['_GETUSERBYIDREQUEST']._serialized_start=114
  _globals['_GETUSERBYIDREQUEST']._serialized_end=146
  _globals['_UPDATEUSERREQUEST']._serialized_start=148
  _globals['_UPDATEUSERREQUEST']._serialized_end=208
  _globals['_DELETEUSERREQUEST']._serialized_start=210
  _globals['_DELETEUSERREQUEST']._serialized_end=241
  _globals['_DELETEUSERRESPONSE']._serialized_start=243
  _globals['_DELETEUSERRESPONSE']._serialized_end=277
  _globals['_LISTUSERSREQUEST']._serialized_start=279
  _globals['_LISTUSERSREQUEST']._serialized_end=297
  _globals['_LISTUSERSRESPONSE']._serialized_start=299
  _globals['_LISTUSERSRESPONSE']._serialized_end=340
  _globals['_USERRESPONSE']._serialized_start=342
  _globals['_USERRESPONSE']._serialized_end=377
  _globals['_USERSERVICE']._serialized_start=380
  _globals['_USERSERVICE']._serialized_end=649
# @@protoc_insertion_point(module_scope)
